# Generated by Django 2.2.7 on 2019-11-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person_Group',
            fields=[
                ('pg_id', models.AutoField(primary_key=True, serialize=False)),
                ('pg_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Person_Group_Person',
            fields=[
                ('pgp_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgp_name', models.CharField(max_length=128)),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_collection.Person_Group')),
            ],
            options={
                'unique_together': {('pgp_id', 'pg_id')},
            },
        ),
        migrations.CreateModel(
            name='FolderName',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(max_length=128)),
                ('folder_path', models.TextField()),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_collection.Person_Group')),
                ('pgp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_collection.Person_Group_Person')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rev_id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.TextField()),
                ('rev_star', models.IntegerField()),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_collection.Person_Group')),
            ],
            options={
                'unique_together': {('rev_id', 'pg_id')},
            },
        ),
    ]
