# Generated by Django 2.2.7 on 2019-11-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldername',
            name='folder_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
